### ISSUE TITLE
Server always showed as sleeping

### ISSUE THREAD

**Issue by Schmoaaaaah** [haveachin/infrared#11]
Every time i try to connect it shows the disconnect message.
Compose:
```
version: '3.3'

services:
  infrared:
    image: haveachin/infrared:latest
    container_name: "infrared"
    restart: "unless-stopped"
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    volumes:
      - "/opt/infrared/configs:/configs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - "25565"
    environment:
      INFRARED_DEBUG: "true"
      INFRARED_COLOR: "false"
      INFRARED_CONFIG_PATH: "/configs"
    links: 
      - mcatm6
      - mcval3mod
      - mcvanilla
```
config:
```
DomainName: "mc.example.com"
ProxyTo: ":25566"
Docker:
  ContainerName: /mcvanilla
Server:
  Version: "1.16.4"
```
