### ISSUE TITLE
Configurating a solution that allows it to select an online server from multiple entries under the same domain

### ISSUE THREAD

**Issue by DressyLemon** [haveachin/infrared#178]
**Is your feature request related to a problem? Please describe.**
I am unable to get players to connect to different server that is running on the same address if for example EU1-GB was down, i'd like it to connect the server EU2-GB.

This below is an example configuration:
```yaml
EU1-GB:
  gateways:
    - default
  domains:
        - "play.server-example.com"
  address: EU1.SERVER-EXAMPLE.COM
EU2-GB:
  gateways:
    - default
  domains:
        - "play.server-example.com"
  address: EU2.SERVER-EXAMPLE.COM
```
even if the player was to connect play.server-example.com it will try and send them to EU1-GB as default even if it was down. - I can't really work out any solutions to this problem.

**Describe the solution you'd like**
I want to be able to "FAIL-OVER" (Not expect it to switch players already existing players as packet transfer isn't a feature for Java), I would like it to instead send players to "EU2.SERVER-EXAMPLE.COM" instead of "EU1.SERVER-EXAMPLE.COM" (if it was for-say down)

**Describe alternatives you've considered**
1. Creating multiple domain name configured for each different region but getting them to connect via dns load-balancer. Don't really want to do this as i've moved away from it for a more logical solution such as infrared as it is more user friendly.

2. From attempts to resolve my resolution, I tried adding doing a little tricky with the domain prefix's but Infrared will use the closest domain to the domain prefix as possible so this didn't work either, for example if my config had the following:
```yaml
EU1-GB:
...
  domains:
        - "*y.server-example.com"
...
EU2-GB:
  ...
  domains:
        - "*.server-example.com"
  ...
```
