### ISSUE TITLE
Specify proxy bind ip

### ISSUE THREAD

**Issue by moom0o** [haveachin/infrared#29]
Is it possible to bind only the proxy -> main server to a different ip?

For example, we have a non ddos protected ip and a ddos protected ip and we would like to connect to the backend with the non protected ip, and want players to connect to the proxy through the protected ip. Is this possible?

**Comment by haveachin** [comment]
Sure! Assuming that you have two network interfaces you could do something like that:

protected.yml
```yaml
DomainName: "protected.example.com"
ListenTo: "{protected-ip}:25565"
ProxyTo: "{server-ip}:25565"
...
```
normal.yml
```yaml
DomainName: "normal.example.com"
ListenTo: "{normal-ip}:25565"
ProxyTo: "{server-ip}:25565"
...
```
